---
version: '3.7'

services:
  vsftpd:
    restart: always
    container_name: vsftpd
    image: vsftpd:latest 
    ports:
    # - "80:5000"
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "${PWD}/opt/sbin:/opt/sbin"
# may come in handy dandy later
#    env_file:
#     - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"`
